#!/usr/bin/env bash

# purpose: point at ntp server

# Define target config files
CONFIG_FILE1="/etc/systemd/timesyncd.conf"
CONFIG_FILE2="/etc/systemd/timesyncd.conf.d/je_ntp.conf"

NTP_SERVER="172.24.241.63"
NTP_fSERVER="rose.jehl.internal"

# Backup the original config file
sudo cp -p "$CONFIG_FILE1" "$CONFIG_FILE1.$(date +%Y%m%d_%H%M%S)"

# Comment out every line in the file
sudo sed -i '/^[[:space:]]*[^#]/ s/^/#/' "$CONFIG_FILE1"
cat "$CONFIG_FILE1"

# 1. Write the desired [Time] block into je_ntp.conf
sudo install -d "$(dirname "$CONFIG_FILE2")"

sudo tee "$CONFIG_FILE2" > /dev/null <<EOF
# Generated by setup script on $(date)
[Time]
NTP=$NTP_SERVER
FallbackNTP=$NTP_fSERVER
EOF

# Restart the timesyncd service
sudo systemctl restart systemd-timesyncd
sudo systemctl status systemd-timesyncd

echo "*"
echo "NTP server set to $NTP_SERVER and systemd-timesyncd restarted."
echo "*"

# Show Time Sync ..
timedatectl show-timesync --all

# Show the last 20 log entries for systemd-timesyncd  ..  journalctl -u systemd-timesyncd.service -n 35
journalctl -u systemd-timesyncd.service -n 20

#