#!/usr/bin/env bash

#find newest files excluding some stuff usually of no interest..

# sort -k1 for newest date and -k3 for size.

find  . -mtime -360 -type f -print0 | xargs -0 stat --printf='%.16y\t%s\t%n\n'  | sort -h -k1 \
   |  grep -v '.git/' | grep -v tmp/ |grep -v x/ |grep -v datasys/ |grep -v sysdata/ \
   | grep -v djangosite/static |grep -v venv |grep -v log/ |grep -v prg/  |grep -v pyc  \
   | tail -n1000

  # |grep gpt


